;;; This file is auto-generated by elreg.py
;;; Do not edit this file manually.

(setq wik-mode-elreg-file-path-begin-regexp "\\(?:^\\|[ \n]\\)\\(?:\\.\\{0,2\\}\\|~\\)?\\(?:/\\|\\\\\\)")

(setq wik-mode-elreg-file-path-end-regexp "\\(?:$\\|[ \n]\\)")

